<?php
/**
 * HiDev plugin for web applications
 *
 * @link      https://github.com/hiqdev/hidev-webapp
 * @package   hidev-webapp
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2017, HiQDev (http://hiqdev.com/)
 */

namespace hidev\webapp\tests\unit\controllers;

use hidev\webapp\controllers\WebAppController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-14 at 11:42:17.
 */
class WebAppControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var WebAppController
     */
    protected $object;
    protected $ip = '1.1.1.1';

    protected function setUp()
    {
        $this->object = new WebAppController('test', null);
    }

    protected function tearDown()
    {
    }

    public function testConstruct()
    {
        $this->assertInstanceOf(WebAppController::class, $this->object);
    }
}
